name: CI Job

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install required packages
      run: |
        sudo apt update
        sudo apt install ffmpeg libsdl2-2.0-0 android-sdk adb build-essential \
                         git pkg-config meson ninja-build libavcodec-dev \
                         libavformat-dev libavutil-dev libsdl2-dev openjdk-8-jdk \
                         mingw-w64 mingw-w64-tools android-tools-adb zip
    - name: allow builder user to write to project directory
      run: chmod -R 777 .
    - name: Release
      run: ./release.sh
    - uses: actions/upload-artifact@v2
      with:
        name: scrcpy
        path: release-*
